#!/bin/sh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

file="$HOME/notes/todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="todo: "

cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file" -fn "tamsyn:size=14" -nb '#101010' -nf '#666666' -sb '#101010' -sf '#ffffff' -bw 10 -h 30)
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file" -fn "tamsyn:size=14" -nb '#101010' -nf '#666666' -sb '#101010' -sf '#ffffff' -bw 10 -h 30)
done

exit 0
