#!/bin/sh
# Info sul sistema in stile notifica (chi ha bisogno di una status bar?)
# Riccardo Palombo - https://riccardo.im
# Preparato per la community Patreon: patreon.com/riccardopalombo

case "$1" in

  -a)
      pkill herbe & \
      herbe "$(date +'%H:%M')" " "\
       		"$(date +'%a, %d %b')" " "\
       		" "\
       		"Volume: $(pamixer --get-volume)%" " "\
            "Batteria: $(acpi | awk -F'[, \t]*' '{print $4}')" " "\
            "$(set -- $(sensors | grep -i core); printf '%s\n' "Temp: $4")" " "\
			"Luminosità: $(xbacklight | cut -f1 -d'.')%" " ";;
 -b)
	pkill herbe & \
	herbe "Batteria al $(acpi | awk -F'[, \t]*' '{print $4}')!";;
 -c)
	pkill herbe & \
	herbe "Resta il $(acpi | awk -F'[, \t]*' '{print $4}')" " "\
	"Chiudo picom!" " "\
	"Abbasso tutto!"	;;

esac
