#!/usr/bin/env bash
#
# Riccardo Palombo - https://riccardo.im
# Preparato per la community Patreon: patreon.com/riccardopalombo
#
# Config per herbstluftwm con Raspberry Pi OS

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#303030'
#feh --bg-center ~/Pictures/rasp-logo.png

hc keyunbind --all
Mod=Mod4   # Tasto Windows / Mod1 per usare Alt
myTerm=urxvt # Terminale preferito
myFM=pcmanfm # File manager preferito
myBorderOne='#222222' # Colore bordo primario
myBorderTwo='#303030' # Colore bordo secondario

hc keybind $Mod-Alt-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-t spawn $myFM
hc keybind $Mod-space spawn rofi -show drun -display-run "" -drun-display-format {name}
hc keybind $Mod-Alt-space spawn rofi -modi todo:~/.config/rofi/rofi-todo.sh -show todo
#hc keybind $Mod-Control-space spawn ~/.config/polybar/scripts/powermenu-alt

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# dividi il frame attuale nella direzione richiesta
# e seleziona la nuova parte
hc keybind $Mod-u chain , split bottom 0.60 , focus down
hc keybind $Mod-o chain , split right 0.5 , focus right

# let the current frame explode into subframes
#hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.04
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags (per replicare scorciatoie Gnome)
hc keybind Control-Alt-Up use_index -1 
hc keybind Control-Alt-Down use_index +1 

# layouting
hc keybind $Mod-r remove
#hc keybind $Mod-s floating toggle # Rendere tutto float
hc keybind $Mod-f fullscreen toggle # Rendere un frame fullscreen
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle # Rendere float il frame attivo
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# Cicla i layout nel frame selezioato (verticale, orizzonale, massimizzato, griglia)
hc keybind $Mod-Shift-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse (valido solo su finestre float)
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus (spostare il focus su monitor e finestre)
#hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
#hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme (da ottimizzare)
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#d7d7af'
hc set frame_border_normal_color $myBorderOne
hc set frame_bg_normal_color $myBorderOne
hc set frame_bg_active_color $myBorderOne
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap -2
hc set frame_padding 0

hc attr theme.active.color $myBorderOne
hc attr theme.normal.color $myBorderOne
hc attr theme.urgent.color $myBorderOne
hc attr theme.inner_width 0
hc attr theme.inner_color $myBorderOne
hc attr theme.border_width 10
hc attr theme.active.inner_color $myBorderOne
hc attr theme.active.outer_color $myBorderOne
hc attr theme.background_color $myBorderOne
hc attr theme.floating.border_width 18
hc attr theme.floating.outer_width 2
hc attr theme.floating.outer_color $myBorderTwo
hc attr theme.floating.active.inner_color $myBorderOne
hc attr theme.floating.active.inner_width 20
hc attr theme.floating.active.outer_color $myBorderTwo

hc set window_gap 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 1

# rules
hc unrule -F
hc rule class='Gimp-2.10' tag=4
hc rule class='Code - OSS' tag=3

hc rule focus=on
hc set focus_follows_mouse 1

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here
# or simply:
hc detect_monitors


# find the panel (avvia Polybar e lascia il suo panel come backup)
panel=~/.config/polybar/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
    hc pad 0 0 0 36 0 # padding bottom per Polybar
done
